default: downloadfile downloadfilestream topKstream phonenumdict main

clean:
	rm downloadfile  downloadfilestream topKstream coinchange phonenumdict main \
	phonedirectory segmenttree tokenbucket

downloadfile:
	g++ -std=c++11 -o downloadfile downloadfile.cpp

downloadfilestream:
	g++ -std=c++11 -g -o downloadfilestream downloadfilestream.cpp

topKstream:
	g++ -std=c++11 -g -o topKstream topKstream.cpp 

phonenumdict:
	g++ -std=c++11 -g -o phonenumdict phonenumdict.cpp

coinchange:
	g++ -std=c++11 -g -o coinchange coinchange.cpp

main:
	g++ -std=c++11 -g -o main main.cpp
segmenttree:
	g++ -std=c++11 -o segmenttree segmenttree.cpp
phonedirectory:
	g++ -std=c++11 -o phonedirectory phonedirectory.cpp
tokenbucket:
	g++ -std=c++11 -g -o tokenbucket tokenbucket.cpp