default: downloadfile downloadfilestream topKstream

clean:
	rm downloadfile  downloadfilestream topKstream

downloadfile:
	g++ -std=c++11 -o downloadfile downloadfile.cpp

downloadfilestream:
	g++ -std=c++11 -g -o downloadfilestream downloadfilestream.cpp

topKstream:
	g++ -std=c++11 -g -o topKstream topKstream.cpp 